//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranMedalManager.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranMedalManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   終了確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QuitConfirmCaption {
            get {
                return ResourceManager.GetString("QuitConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了する前に変更を保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QuitConfirmText {
            get {
                return ResourceManager.GetString("QuitConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   save.csv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFileName {
            get {
                return ResourceManager.GetString("SaveFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	譜面レベル	LV1譜面初プレー	ブロンズ	LV1の楽曲をプレーする
        ///2	譜面レベル	LV2譜面初プレー	ブロンズ	LV2の楽曲をプレーする
        ///3	譜面レベル	LV3譜面初プレー	ブロンズ	LV3の楽曲をプレーする
        ///4	譜面レベル	LV4譜面初プレー	ブロンズ	LV4の楽曲をプレーする
        ///5	譜面レベル	LV5譜面初プレー	ブロンズ	LV5の楽曲をプレーする
        ///6	譜面レベル	LV6譜面初プレー	ブロンズ	LV6の楽曲をプレーする
        ///7	譜面レベル	LV7譜面初プレー	ブロンズ	LV7の楽曲をプレーする
        ///8	譜面レベル	LV8譜面初プレー	ブロンズ	LV8の楽曲をプレーする
        ///9	譜面レベル	LV9譜面初プレー	ブロンズ	LV9の楽曲をプレーする
        ///10	譜面レベル	LV10譜面初プレー	ブロンズ	LV10の楽曲をプレーする
        ///11	譜面レベル	LV11譜面初プレー	ブロンズ	LV11の楽曲をプレーする
        ///12	譜面レベル	LV12譜面初プレー	ブロンズ	LV12の楽曲をプレーする
        ///13	バージョン・譜面別	1st N譜面初プレー	ブロンズ	1stの楽曲ノーマル譜面をプレーする
        ///14	バージョン・ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TranMedalData {
            get {
                return ResourceManager.GetString("TranMedalData", resourceCulture);
            }
        }
    }
}
